# Generated by Django 6.1 on 2026-08-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, help_text='Used to send add/edit/delete expense notifications.', max_length=254, null=True),
        ),
    ]
